// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_TlME9-H1NJeATsBFil7IOoPlmBGAfc',
    appId: '1:992459327172:web:715205830560e7ab006b91',
    messagingSenderId: '992459327172',
    projectId: 'canteen-online-2946d',
    authDomain: 'canteen-online-2946d.firebaseapp.com',
    storageBucket: 'canteen-online-2946d.firebasestorage.app',
    measurementId: 'G-DN8WHPWHLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCst0a7XPmCg3FWQnVmoj4IOil2ixeEXd4',
    appId: '1:992459327172:android:085ec991e2fb942e006b91',
    messagingSenderId: '992459327172',
    projectId: 'canteen-online-2946d',
    storageBucket: 'canteen-online-2946d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm8CF8was5XgYBIq5AGXrQ9cl4EBt47t0',
    appId: '1:992459327172:ios:7878c40d787ee1ff006b91',
    messagingSenderId: '992459327172',
    projectId: 'canteen-online-2946d',
    storageBucket: 'canteen-online-2946d.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm8CF8was5XgYBIq5AGXrQ9cl4EBt47t0',
    appId: '1:992459327172:ios:7878c40d787ee1ff006b91',
    messagingSenderId: '992459327172',
    projectId: 'canteen-online-2946d',
    storageBucket: 'canteen-online-2946d.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh_TlME9-H1NJeATsBFil7IOoPlmBGAfc',
    appId: '1:992459327172:web:b3d4c2c6eefacdd6006b91',
    messagingSenderId: '992459327172',
    projectId: 'canteen-online-2946d',
    authDomain: 'canteen-online-2946d.firebaseapp.com',
    storageBucket: 'canteen-online-2946d.firebasestorage.app',
    measurementId: 'G-97X2ZR5BL4',
  );
}
